### ISSUE TITLE
[Feature Request] Acrylic Support

### ISSUE THREAD

**Issue by ghost** [Vencord/Desktop#16]
While this is a **Windows** only solution, it does add some very nice additions for theme creators.

And since it's not exactly night and day to simply switch out an ASAR for transparency anymore, I think if Vencord Desktop added support for Vibe it would attract more users.

More about vibe here: https://github.com/pykeio/vibe

**Comment by Void48** [comment]
> While this is a **Windows** only solution, it does add some very nice additions for theme creators.
> 
> And since it's not exactly night and day to simply switch out an ASAR for transparency anymore, I think if Vencord Desktop added support for Vibe it would attract more users.
> 
> More about vibe here: https://github.com/pykeio/vibe

I agree. acrylic and mica support wen 😔🙏

**Comment by ZeldrexK0DE** [comment]
why? acrylic and mica makes some apps laggy asf

**Comment by DeadVoxels** [comment]
Acrylic hasn't affected performance on my devices very much, at least from experience. And even then, it'd be an optional feature. If it's too laggy for you or anyone else then just keep that feature disabled on your client. No need to prevent those like me who like the look it allows for, from using the feature when it'd be an optional one.

**Comment by Vendicated** [comment]
Electron supports this natively now (https://github.com/electron/electron/pull/38163), so vibe is obsolete

iirc, flag was working on adding this via electron's new api

**Comment by Vendicated** [comment]
this is now available in v0.2.7 thanks to flag
