### ISSUE TITLE
[Feature Request] FileViewer Plugin

### ISSUE THREAD

**Issue by Pierre2004** [Vencord/Desktop#24]
https://betterdiscord.app/plugin/FileViewer
![FileDemo](https://user-images.githubusercontent.com/79320512/235986072-d7ea5de0-8e14-4331-a75e-2e4dc2f7e131.gif)
https://github.com/TheGreenPig/BetterDiscordPlugins/blob/918c1d43b826dfb51870f0fc518993597b1d5e4f/FileViewer/FileViewer.plugin.js

**Comment by Vendicated** [comment]
this is very much not the correct place for this request
