### ISSUE TITLE
[Bug] Vencord keeps unloading itself.

### ISSUE THREAD

**Issue by Felix-Jay** [Vencord/Desktop#28]
Sometimes I just log into discord and it's back to being normal discord, so I have to go back here and reinstall it. Please fix this!

**Comment by Redundakitties** [comment]
you can just run the exe you used to install it again, no need to redownload it from the github! plus your settings, plugins, and customcss will all be saved upon re-installing so do not fret :)

**Comment by Vendicated** [comment]
wrong repo and not doable, just repatch if it happens
