### ISSUE TITLE
[Feature Request] middle mouse button scrolling (autoscrolling) on linux

### ISSUE THREAD

**Issue by cclockworks** [Vencord/Desktop#31]
one thing missing on vencord desktop compared to webcord is middle mouse scrolling on linux. it's honestly a feature i can't live without personally

**Comment by Vendicated** [comment]
this should be a plugin request on the main repo

**Comment by cclockworks** [comment]
ok an easy way to achieve this is by running vesktop with the `--enable-blink-features=MiddleClickAutoscroll` flag

**Comment by TheKodeToad** [comment]
...but on linux it does mean you paste every time you scroll in chat :/

However, i think webcord has an option which (somehow with weird magic stuff) adds the option
