### ISSUE TITLE
Where are the plugins located?

### ISSUE THREAD

**Issue by BarackObamaCouncil** [Vencord/Desktop#41]
Hello, I would like to develop my own plugin, I have already implemented it on the full version of Vencord and I would also like to implement it here, however I can't find which file or folder contains the plugins, I looked through all the source code and couldn't find a match, help is very appreciated.

**Comment by Vendicated** [comment]
it just uses normal vencord, nothing special. Open Desktop settings and sxro down to load a custom build of vencord
