### ISSUE TITLE
Add ability to disable the spell checker

### ISSUE THREAD

**Issue by FichteFoll** [Vencord/Desktop#43]
It is currently not possible to disable the spell checker for text input. In normal Discord, this can be accomplished using the context menu, but such an item is missing in Vencord Desktop. I also tried disabling it in the local storage [as instructed by the help page][help], but the `SpellcheckStore` key didn't exist for me.

[help]: https://support.discord.com/hc/en-us/articles/360000877191-Spellcheck-in-Discord

**Comment by Vendicated** [comment]
https://github.com/Vencord/Desktop/commit/7f54858b274f9a884305d5ced96f368535bef8e2

**Comment by FichteFoll** [comment]
Thanks for the fast implementation. :heart: I can confirm that this is working.
